### ISSUE TITLE
Tip to jump back in operator-pending mode

### ISSUE THREAD

**Issue by bimlas** [haya14busa/vim-easyoperator-line#4]
The plugin is good, but I missing the "jump-back after operation" behaviour (like delete and yanking doesit). Here's a method to solve the problem:

```
omap  <Plug>(easymotion-prefix)l  :<C-u>call easyoperator#line#selectlines() <Bar> call feedkeys('<C-O>')<CR>
```

I think it's more universal than creating standalone functions for every operator.

**Comment by coachshea** [comment]
@BimbaLaszlo I'm curious as to when you use this feature. It is already instituted for yank and delete as you mention. It wouldn't be much use with change or visual mode (personally I find that easymotion and easyoperator-line significantly lessen my need for visual mode in the fist place). I apologize if I'm missing something simple, but I'm just trying to understand the rationale (and incorporate it if it's something that I would use). Thanks for your time.

**Comment by bimlas** [comment]
For example I can comment a block, visually select it, raise indent, etc. without moving the cursor.

**Comment by coachshea** [comment]
Thanks for the reply. For my own work-flow, I can definitely see the value of 
commenting/uncommenting blocks without moving the cursor. I hadn't thought of 
that previously. Thanks for sharing your thoughts.
